Update README.md
ottoeprz/glowing-engine pull request #1
Opened 2022-09-21 14:13 UTC by ottoeprz

objetivo 0

2022-09-21 17:45 UTC, JJ commented
No has realizado la lista de comprobación, así que posiblemente haya algún error. Para empezar, no has puesto la configuración.

2022-09-21 17:45 UTC, JJ requested changes
Ni describe un problema, ni explicita la lógica de negocio, ni justifica que esté en la nube.

2022-09-22 08:13 UTC, ottoeprz commented
* [x ] ¿Se trata de un problema real del que se tenga conocimiento personal?
Si, durante mi vida he sido un gran apasionado de la psicología, sobre todo del tema de la salud mental.
* [x ] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
Si ya que así podremos obtener cada vez más información, tener el servicio disponible para más clientes e ir actualizándolo cuando sea necesario
* [x ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
Si, la solución tiene su adecuada lógica empresarial para trabajar, crear, almacenar y procesar los datos correctamente
* [ x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?
Si habrán ciertos enlaces, imágenes y o documentación necesaria enlazada desde el readme

2022-09-22 09:44 UTC, JJ commented
Esto lo tenéis que poner en el cuerpo del PR. Pedidme también revisión explícitamente, cuando hayáis hecho todos los cambios.

2022-09-22 14:14 UTC, ottoeprz commented
como voy al cuerpo de pr, ya he modificado el readme, puedes mirarlo

2022-09-22 15:32 UTC, JJ commented
> como voy al cuerpo de pr, ya he modificado el readme, puedes mirarlo

[Esto](https://github.com/ottoeprz/glowing-engine/pull/1#issue-1381006608) es el cuerpo del PR.

2022-09-22 15:36 UTC, JJ requested changes
Ni se comprende demasiado bien el problema, ni está clara la lógica de negocio, ni que sea en la nube. Tratándose de estado mental, lo mejor es que *no* esté en la nube por protección de datos.
Por favor, revisa bien los conceptos de Design Thinking y trata de encontrar un problema con el que puedas trabajar.

2022-09-22 15:36 UTC, JJ commented on README.md
> +Dicho proyecto será conocido como "Mental Health" se basara en un repositorio situado en la nube, el cual podrá extraer y analizar el estado mental de un usuario tras una serie de preguntas para dete
1. ¿Tienes conocimiento personal de este problema? ¿"Conocer" el "estado mental" ayuda a qué? ¿Cuál es el dominio del problema? ¿Qué es el estado mental? ¿Qué procesamiento de dato y a partir de qué datos?
2. ¿"Ver artículos" significa que le vas a pasar enlaces? ¿Eso qué resuelve?

2022-09-22 15:36 UTC, JJ commented on README.md
> +El análisis se realizará a través de un algoritmo de filtrado sencillo diseñado por mí, el cual filtre contenido que se encuentra open source en todo internet, tras las determinadas respuestas del te
*Todo* internet es un poco grande. "Filtrar" ¿de dónde? ¿Lo tienes almacenado en una base de datos? ¿Vas a filtrar de acuerdo a qué?

2022-09-24 13:29 UTC, ottoeprz commented
> Ni se comprende demasiado bien el problema, ni está clara la lógica de negocio, ni que sea en la nube. Tratándose de estado mental, lo mejor es que _no_ esté en la nube por protección de datos. Por favor, revisa bien los conceptos de Design Thinking y trata de encontrar un problema con el que puedas trabajar.

profe yo no soy muy bueno redactando y explicándome pero creo que la idea tiene sentido ya que puede crecer exponencialmente junto a las necesidades de un usuario sin ser una idea y un trabajo tan complicado, en esta asignatura hasta donde vamos a llegar más o menos en fin de curso?
Yo solo necesito un poco de guía en todo en este tema ya que es la primera asignatura que tengo relacionada con el cloud computing, estoy en ello cambiando todo para explicar mejor la problemática.

2022-09-25 09:59 UTC, ottoeprz commented
profe ya he actualizado el readme, puede revisarlo

2022-09-29 05:30 UTC, JJ requested changes
Has reescrito más o menos lo que quieres hacer, pero ni es un problema que sea adecuado para la asignatura (lee en el guión cuales son apropiados o no) ni la solución que propones lo soluciona (y por tanto no se puede validar) o es adecuada para la asignatura por no tener clara la lógica de negocio.

2022-09-29 05:30 UTC, JJ commented on README.md
> +Hoy en día los índices de depresión y suicidio son cada vez más elevados, el número de redes sociales ha ido aumentando y la personas no paran de observar la vida y las opiniones de los demás. No se
De veras, Otto, que no veo esto como una aplicación para la asignatura ni creo que puedas ir por ahí. Es algo que tienes que programar, y los problemas físicos son difíciles de validar. Voy a seguir leyendo, pero creo que deberías cambiar totalmente de ámbito.

2022-09-29 05:30 UTC, JJ commented on README.md
> +Para ello procederé con la realización de un proyecto alojado en la nube. Dicho proyecto será conocido como "Glowing Engine", relacionado con la salud mental, que cuando hablamos de ella nos referimo
¿Qué es *ello*? Si mencionas un problema, el programa debería solucionarlo. Y ya os he dicho que los problemas físicos simplemente no los puedes solucionar, porque no puedes validarlos.

2022-09-29 05:30 UTC, JJ commented on README.md
> +Dicho proyecto consisitirá en un aplicación situada en la nube la cual tendrá una página de inicio donde el usuario verá algún tipo de introducción sobre el contenido de la misma, y que este pueda da
Deberías empezar describiendo la página de negocio. Ya os he dicho que no se va a hacer ningún *front-end*. No propongas soluciones que no vas a poder hacer.

2022-10-03 17:04 UTC, ottoeprz commented
Buenas profe ya he cambiado completamente la temática de mi problema, puede revisarlo

2022-10-03 17:07 UTC, ottoeprz commented
@JJ

2022-10-03 17:10 UTC, JJ requested changes
Quizás sería conveniente que buscaras algún problema del que ya haya datos entre los que os he enlazado desde el guión. Ánimo.

2022-10-03 17:10 UTC, JJ commented on README.md
> +Emprende en tu vida con nuestro servidor en la nube.
Esto no es un planteamiento de un problema. "Servidor" tampoco es lo que vamos a hacer.

2022-10-03 17:10 UTC, JJ commented on README.md
> +Para ello propondre una aplicación en la nube, abierta para todos los usuarios, la cual recoja ciertos datos como número de integrantes de la familia, horas de trabajo a la semana, salario mensual y/
Se trata de simples operaciones aritméticas, y sobre datos que tendría que meter el usuario. Os he comentado repetidamente que el usuario debería meter cero datos. Por favor, revisa el guión, incluyendo el nuevo ítem en la lista de comprobación.

2022-10-03 17:22 UTC, ottoeprz commented on README.md
> +Para ello propondre una aplicación en la nube, abierta para todos los usuarios, la cual recoja ciertos datos como número de integrantes de la familia, horas de trabajo a la semana, salario mensual y/
Este problema no ve posible abordarlo en la asigantura entonces? Son operaciones sencillas la cuales su eficacia puede alimentarse de la interaccion con la nube sin ningun problema, tiene una logica de negocio concreta en mi opinion. El usuario no tiene que generar ningun dato ya que los datos ya vendran introducidos previamente, de alguna empresa, y/o articulo o cualquier dato correspondiente a las ganancias de un area de la poblacion @JJ

2022-10-03 17:27 UTC, JJ commented on README.md
> +Para ello propondre una aplicación en la nube, abierta para todos los usuarios, la cual recoja ciertos datos como número de integrantes de la familia, horas de trabajo a la semana, salario mensual y/
Mira, por favor, lo que se considera lógica de negocio aceptable para este proyecto.

2022-10-13 17:08 UTC, ottoeprz commented
@JJ He modificado el readme y los test de comprobación.

2022-10-13 17:43 UTC, JJ requested changes
¿De qué forma es "más cercana" una lógica de negocio sustancial en línea con lo solicitado por este objetivo? ¿De qué forma "encontrar pista de pádel" es un problema real?

2022-10-13 22:25 UTC, ottoeprz commented
@JJ

2022-10-14 05:22 UTC, JJ requested changes
Cambiar unas cuantas frases no crea lógica de negocio de repente. Por favor, trata de buscar un problema que sea real y que implique procesamiento de información con una lógica de negocio no trivial. Y por favor, plantéate un plazo corto (días) porque hay que seguir trabajando en el resto de los objetivos. Te agradezco que hayas hecho este cambio tan rápidamente, te agradecería que este también lo hicieras de la misma forma. Si quieres, en clase.

2022-10-14 05:22 UTC, JJ commented on README.md
> +PadelGlow tendrá como funcion principal resolver este problema. Facilitando así la ubicación y reserva de las pistas de padel mas cercanas que esten disponibles para una reserva en un periodo de tiem
¿De qué forma esto cambia la lógica de negocio?

2022-10-14 05:22 UTC, JJ commented on README.md
> +Generalmente aquí en granada y en muchas de nuestras ciudades disponemos de una gran cantidad de pistas de pádel, pero no una forma facil de acceder a ellas, generalmente tenemos que estar haciendo b
¿De qué forma esto hace que el problema sea más real? "Hacer búsquedas tediosas" no es un problema.

2022-10-18 17:26 UTC, ottoeprz commented
Vale profe, ya he actualizado completamente el readme, he seguido en el mismo tema a ver si puedo seguir trabajando en esta rama ya que he estado buscando y no he conseguido otro tema con el que familiarizarme. Y muchas gracias por la retroalimentación, es de gran ayuda aunque no lo parezca. @JJ

2022-10-18 17:59 UTC, JJ approved these changes
Gracias por seguir intentándolo. Esto parece más un problema, aunque realmente tendrás que formularlo en los objetivos sucesivos para que tenga suficiente envergadura para poder trabajar con él en una aplicación nativa en la nube (algo que, por cierto, no has justificado). También tendrás que concretar la lógica de negocio. Si lo haces antes del siguiente PR, mejor; si no tendrás que concretarlo en un milestone en el siguiente objetivo.

2022-10-18 20:04 UTC, merged