Add files via upload
ottoeprz/glowing-engine pull request #2
Opened 2022-10-31 18:24 UTC by ottoeprz

2022-11-11 11:41 UTC, ottoeprz commented
Buenas profe, aquí le dejo mi objetivo 1 listo para revisión @JJ

2022-11-11 16:24 UTC, JJ commented
Por favor, entrégalo correctamente.

2022-11-11 17:28 UTC, ottoeprz commented
Me faltaba el pull request al archivo del objetivo 1, ya esta hecho, pero me da error en el tick de los milestones y no entiendo por qué. @JJ

2022-11-11 18:41 UTC, JJ commented
pues conviene que lo entiendas, porque son los requisitos para evaluarlo

2022-11-11 20:45 UTC, ottoeprz commented
Me aparece que no tengo ni un milestone, por eso me falla, y si lo tengo. @JJ

2022-11-14 17:25 UTC, pablo1mc315 requested changes
Buenas @ottoeprz!! Se me ha asignado como revisor de tu PR. Te he dado unos pequeños consejos de cosas que creo que puedes mejorar en el objetivo. Échales un ojo y animo! 💪🏼

2022-11-14 17:25 UTC, pablo1mc315 commented on docs/milestones.md
> +- [ ] [M1]: Construir métodos en fichero/ficheros que puedan realizar:
Construir métodos en un fichero/ficheros no constituye un PMV, es decir, algo que se le pueda entregar al cliente y que tenga una mínima funcionalidad.

2022-11-14 17:25 UTC, pablo1mc315 commented on docs/milestones.md
> +- [ ] [M0]: Implementación de una estructura de datos en un fichero/ficheros que permita:
¿Cómo sabemos si hará falta un fichero o varios? En mi opinión deberías concretar un pelín más :)

2022-11-14 17:25 UTC, pablo1mc315 commented on docs/user-stories.md
> +  - [HU5] Pedro solo quiere darse un partido relajante con sus vecinos, donde pueda divertirse y reirse.
Dale una vuelta a las HU, ¿no crees que casi todas implican la misma funcionalidad pero modificando el motivo?

2022-11-15 11:11 UTC, fjgallardo00 reviewed
Hola @ottoeprz , se me ha asignado como revisor del PR, así que voy a echarte una mano para que puedas completar el objetivo lo antes posible. Como @pablo1mc315 ya te ha dicho varias cosas, voy a dar un detalle nada más.

2022-11-15 11:11 UTC, fjgallardo00 commented on docs/milestones.md
> +  - Obtener la mejor pareja dado un motivo de partido específico con la utilizacion del método greedy
A parte de lo que ha dicho Pablo sobre los ficheros, quiero añadir que mi consejo es que enfoques el M0 al modelo del problema y el M1 a la lógica de negocio. Estos Milestones, y sobre todo el M0, deben de estar bien explicados para que otra persona pueda entender lo que tiene que hacer si trabajara sobre tu proyecto.

2022-11-15 15:50 UTC, ottoeprz commented
Buenas, les agradezco mucho su ayuda, ya he modificado en torno a lo que me recomendaron, un saludo. @fjgallardo00 @pablo1mc315.

2022-11-15 16:18 UTC, pablo1mc315 commented
Los milestones los veo mejor distribuidos, aunque quizá los explicaría un poco más y con más detalle (sin dar detalles de implementación) para que, de cara a otros objetivos, la persona que tenga que trabajar sobre tu proyecto lo tenga todo más claro. Pero ya te digo, los veo bien 👍🏼.

En cuanto a las HU no entiendo muy bien que es lo que has modificado, puesto que las veo prácticamente iguales :)

2022-11-15 17:15 UTC, fjgallardo00 commented
Los milestones están mejor definidos, pero veo que siguen escritos como implementación de una estructura de datos o método. Las estructuras de datos y los métodos como tal no son PMV, no es algo que se le pueda entregar al cliente. Dale una pequeña vuelta a ese detalle.

Las HU yo también las veo iguales, no veo apenas cambios.

Dale una vueltecilla a todo. Ánimo!!

2022-11-18 11:42 UTC, ottoeprz commented
Vale , ahora como lo ven? He modificado los milestones y las hus. @pablo1mc315 @fjgallardo00

2022-11-18 17:23 UTC, ottoeprz commented
@JJ, Listo para revision.

2022-11-18 19:05 UTC, JJ requested changes
Por favor, trata de entender lo que acertadamente te han apuntado los revisores. Revisa también el material de este objetivo, y el material impartido en clase.

2022-11-18 19:05 UTC, JJ commented on docs/milestones.md
> +- [ ] [M0]: Implementación de una cadena de estructura de datos en distintos ficheros que permita:
Creo que estás mencionando algo, una "cadena de estructura de datos", que yo no conozco.
En todo caso, es difícil implementar si no se entiende el problema, así que es difícil que quien programe sepa lo principal, qué hacer.

2022-11-18 19:05 UTC, JJ commented on docs/milestones.md
> +- [ ] [M1]: Diseño de un método que forme parte de un módulo, en un fichero que permita:
¿Sólo un método, y sólo un módulo?

2022-11-21 19:10 UTC, ottoeprz commented
Ya he corregido los milestones adecuadamente espero, le pido revision nuevamente @JJ .

2022-11-21 19:17 UTC, JJ commented
Creo que sigues sin entender cómo empezar el desarrollo de un proyecto. Sigues combinando palabras de diferentes formas, pero sin tratar de entender qué es un milestone, qué se espera de un milestone 0, y qué se espera de un milestone 1 o sucesivos.
Ya te lo han dicho los compañeros. Está escrito en los errores frecuentes. Por favor, trata de entender los conceptos que se tratan de plasmar en este objetivo y luego actúa en consecuencia.

2022-11-22 18:36 UTC, ottoeprz commented
@JJ Ya he mirado nuevamente los contenidos y las transparencias, le solicito revision nuevamente @JJ .

2022-11-22 18:52 UTC, JJ approved these changes
Lo voy a a aceptar, pero por favor aclara las cosas bien antes de llegar al siguiente objetivo. Recuerda que lo que pongas aquí también tiene que estar en los milestones del repositorio.

2022-11-22 18:52 UTC, JJ commented on docs/milestones.md
> +- [ ] [M0]: Ficheros que contengan el modelo del problema:
¿Ficheros o una estructura? ¿Una sola estructura?

2022-11-22 18:56 UTC, ottoeprz commented on docs/milestones.md
> +- [ ] [M0]: Ficheros que contengan el modelo del problema:
Ahora mismo modifico los milestones antes de hacer el merge.

2022-11-22 19:05 UTC, merged