[IV 22-23] : Objetivo 2
ottoeprz/glowing-engine pull request #6
Opened 2022-12-10 16:02 UTC by jesusjmma

**Sobre la estructura del repositorio**:
* [x] ¿He seguido las mejores prácticas en nombre de las clases y ficheros y disposición de los mismos?

**Sobre el análisis del problema**:
* [x] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo que se ha creado?
* [x] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor, una entidad o un agregado?
* x] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo objeto valor que no dependa de ningún otro (y que sea la base de muchos otros)?.

**Sobre la planificación y la programación**:
* [x] ¿Los issues representan un problema, y no una tarea?
* [x] ¿Todos los mensajes de commit explican el cambio, y no se limitan a repetir el nombre del fichero que se ha cambiado?
* [x] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [x] ¿Se ha hecho una revisión real del código para comprobar que todos los atributos y funciones creadas están respaldadas por una HU?
* [x] ¿Todos los issues creados están asignados a una HU?
* [x] ¿Todos los cambios en el código están asignados a un issue al que se referencia en un commit? Los issues sobre los que estoy trabajando, ¿han sido asignados al primer milestone?
* [x] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [x] ¿Son los milestones sobre los que estoy trabajando productos mínimamente viables? ¿O tengo que solicitar al product manager que cree milestones adicionales o precise de qué producto se trata?
* [x] ¿Se ha comprobado que el código entregado sea sintácticamente correcto?

2022-12-10 16:03 UTC, jesusjmma commented
Hola @ottoeprz.
Está listo para revisión por tu parte este Pull Request con el Objetivo 2.

2022-12-11 13:01 UTC, ottoeprz commented
Buenas!!! @jesusjmma,  yo lo veo bien. Aprobado!

2022-12-12 17:54 UTC, jesusjmma commented
@ottoeprz asigna cuando puedas al PR al Milestone 0

2022-12-13 16:04 UTC, ottoeprz commented
Listo.

2022-12-16 16:41 UTC, JJ commented
Primero, tienes que aprobar explícitamente. Segundo, debéis pedirme revisión.

2022-12-16 16:42 UTC, JJ commented
Los commits no siguen las buenas prácticas, evidenciando que no se está siguiendo el procedimiento correcto para desarrollar atendiendo a las necesidades del cliente.

2022-12-16 16:44 UTC, JJ requested changes
Por favor, mira los errores frecuentes sobre este objetivo y los objetivos de aprendizaje de las últimas semanas. En concreto, si no se desarrolla a partir de una historia de usuario es imposible llegar a una solución adecuada.

2023-01-14 15:50 UTC, jesusjmma commented
@JJ he corregido todo lo mencionado y queda aprobado por mi parte:

- En primer lugar he leído todos los errores frecuentes de este objetivo y los objetivos de aprendizaje de todas las semanas.
- He vuelto a crear los commits siguiendo las mejores prácticas tal y como he encontrado en varios sitios ([como este](https://www.freecodecamp.org/espanol/news/como-escribir-un-buen-mensaje-de-commit/)).
- He elegido una historia de usuario donde se explicaba mejor la necesidad que había y de donde realmente había sacado el modelo del problema que había creado.

¿Lo podría revisar @JJ?

2023-01-16 06:25 UTC, JJ commented
Ninguno de los tres últimos commits sigue las mejores prácticas.

2023-01-16 09:26 UTC, jesusjmma commented
> Ninguno de los tres últimos commits sigue las mejores prácticas.

¿Dónde podría ver las mejores prácticas a seguir? He buscado en varios sitios y he intentado seguir lo que decían.

2023-01-16 09:34 UTC, JJ commented
> > Ninguno de los tres últimos commits sigue las mejores prácticas.
> 
> ¿Dónde podría ver las mejores prácticas a seguir? He buscado en varios sitios y he intentado seguir lo que decían.

Las hemos repetido en clase muchas veces, pero no puedo creerme que no seas capaz de encontrar una lista de mejores prácticas en mensajes de commit y me las tengas que preguntar a mi. No es *mi* lista, es *la* lista.

2023-01-16 15:04 UTC, jesusjmma commented
Buenas tardes @JJ.

He abierto un nuevo issue (#7) donde he intentado que se plantee correctamente la formulación del problema que había hecho.

He hecho de nuevo los commits de este pull request siguiendo las siguientes buenas prácticas:

- Títulos cortos (max 50 caracteres). Previamente había hecho los títulos largos de mal, lo cual es un error.
- Títulos con verbos en imperativo. En los commits iniciales esto no lo había hecho bien.
- Usado un prefijo en los títulos para hacerlos más fácilmente legibles y especificar el tipo del commit.
- Línea en blanco entre el título y el cuerpo del commit, así como entre los diferentes párrafos del commit.
- Explicación concisa del motivo en el cuerpo del commit para añadir el contexto necesario.
- No usar puntos finales ni poner signos de puntuación innecesarios.
- Poner mayúscula al inicio del título y de cada línea.

¿Podría volver a revisar, por favor?

2024-11-24 18:22 UTC, closed without merging